#!/bin/sh
# A very simple script for updating any HTTP-based DynDNS service
# Had to be written because joker.com's DYNA just wouldn't work with anything else.
#    -- Matthias Rampke, Jan. 2011

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.

# made with much info and insiration from https://forum.openwrt.org/viewtopic.php?id=14040

set -e

if [ -z $DDNS_CONF ]; then
    if [ -r simple-ddns.conf ]; then
        DDNS_CONF=./simple-ddns.conf
    elif [ -r /etc/simple-ddns.conf ]; then
        DDNS_CONF=/etc/simple-ddns.conf
    else
        echo "No config file found (use ./simple-ddns.conf, /etc/simple-ddns.conf or set DDNS_CONF)"
        exit 1
    fi
fi

. $DDNS_CONF

[ -z $HOST ] && HOST="members.dyndns.org"
[ -z $CHECKIP_URL ] && CHECKIP_URL="http://checkip.dyndns.org"
[ -z $CHECKIP_STRING ] && CHECKIP_STRING="Current IP Address: "
[ -z $TMPFILE ] && TMPFILE=/tmp/simple-ddns.ip

# URL may not yet be set ...
[ -z $URL ] && URL=""

# from here on, do not accept missing variables
set -u

# ... but we really want the unbound-variables-check when setting it
[ -z $URL ] && URL="http://$USER:$PASSWORD@$HOST/nic/update?hostname="

alias CURL="curl -s"
# if you don't have curl:
#alias CURL="wget -q -O -"
#alias CURL="fetch -q -o -"

# some builtin echo doesn't support -n
alias echo=/bin/echo
# from https://forum.openwrt.org/viewtopic.php?id=14040
IP_ADDR_RE="[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}"

# get IP address
IP=`CURL $CHECKIP_URL | grep "$CHECKIP_STRING$IP_ADDR_RE"| sed "s/^.*$CHECKIP_STRING\($IP_ADDR_RE\).*$/\1/"`

# exit if IP didn't change
if [ -r $TMPFILE ]; then
    if [ $IP = "`cat $TMPFILE`" ]; then
        exit 0
    fi
fi
echo $IP > $TMPFILE

for DOMAIN in $DOMAINS; do
    echo -n `date -u "+[%Y-%m-%d %H:%M]"` "$DOMAIN: "
    CURL "$URL$DOMAIN"
done
