#!/bin/sh
# A very simple script for updating any HTTP-based DynDNS service
# Had to be written because joker.com's DYNA just wouldn't work with anything else.
#    -- Matthias Rampke, Jan. 2011

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details.


set -e

if [ -z $DDNS_CONF ]; then
    if [ -r ddns.conf ]; then
        DDNS_CONF=./ddns.conf
    elif [ -r /etc/ddns.conf ]; then
        DDNS_CONF=/etc/ddns.conf
    else
        echo "No config file found (use ./ddns.conf, /etc/ddns.conf or set DDNS_CONF)"
        exit 1
    fi
fi

. $DDNS_CONF

# from here on, do not accept missing variables
set -u
